Hw03 mongodb
yaroslava-yemets/nodejs-homework-rest-api pull request #2
Opened 2021-11-14 17:03 UTC by yaroslava-yemets

added files and code for using contacts information from database

2021-11-15 14:36 UTC, TViglesGoom requested changes

2021-11-15 14:36 UTC, TViglesGoom commented on .env
> +DB_HOST=mongodb+srv://Yaroslava:7Q62OQG7oMRBKL8y@cluster0.a6e8q.mongodb.net/phonebook?retryWrites=true&w=majority
.env file не должен быть запушен в репозиторий, тем более, с реальными данными. Это очень грубая ошибка.

2021-11-15 14:36 UTC, TViglesGoom commented on validations/contact.js
> +const joiContactSchema = Joi.object({
Точно такая же схема есть в models/contact.js. Она точно нужна и там, и там?

2021-11-15 21:06 UTC, yaroslava-yemets commented on .env
> +DB_HOST=mongodb+srv://Yaroslava:7Q62OQG7oMRBKL8y@cluster0.a6e8q.mongodb.net/phonebook?retryWrites=true&w=majority
удалила из гитхаба, добавила в гитигнор

2021-11-15 21:06 UTC, yaroslava-yemets commented on validations/contact.js
> +const joiContactSchema = Joi.object({
Удалила ненужный файл

2021-11-16 15:52 UTC, TViglesGoom approved these changes

2021-11-16 21:40 UTC, merged