added authentication, login, logout
yaroslava-yemets/nodejs-homework-rest-api pull request #3
Opened 2021-11-20 22:47 UTC by yaroslava-yemets

added registration, login, logout, work with requests only when user is unauthorized and some pagination

2021-11-21 21:47 UTC, KirillKulakow commented on controllers/auth/login.js
> +  //   if (!user) {
удалить

2021-11-21 21:47 UTC, KirillKulakow commented on controllers/auth/login.js
> +// const bcrypt = require('bcryptjs')
удалить

2021-11-21 21:47 UTC, KirillKulakow commented on controllers/auth/register.js
> +  //   const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10))
удалить

2021-11-21 21:47 UTC, KirillKulakow commented on controllers/auth/register.js
> +// const bcrypt = require('bcryptjs')
удалить

2021-11-21 21:52 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  const { page, limit } = req.query
нужно делать проверку на page и limit
если не число - вернуть ошибку badRequest

2021-11-21 21:56 UTC, KirillKulakow commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
если я сделаю запрос на список контактов без авторизации - приложение сломается

2021-11-21 21:57 UTC, KirillKulakow commented on routes/api/auth.js
> +router.get('/logout', authenticate, controllerWrapper(ctrl.logout))
шаг 5 пропущен

2021-11-21 21:58 UTC, KirillKulakow requested changes
Need fix

2021-11-22 12:46 UTC, yaroslava-yemets commented on controllers/auth/login.js
> +  //   if (!user) {
Удалила

2021-11-22 12:46 UTC, yaroslava-yemets commented on controllers/auth/login.js
> +// const bcrypt = require('bcryptjs')
Удалила

2021-11-22 12:47 UTC, yaroslava-yemets commented on controllers/auth/register.js
> +  //   const hashPassword = bcrypt.hashSync(password, bcrypt.genSaltSync(10))
Удалила

2021-11-22 12:47 UTC, yaroslava-yemets commented on controllers/auth/register.js
> +// const bcrypt = require('bcryptjs')
удалила

2021-11-22 12:47 UTC, yaroslava-yemets commented on controllers/contacts/listContacts.js
> +  const { page, limit } = req.query
Сделала проверку

2021-11-22 12:47 UTC, yaroslava-yemets commented on middlewares/authenticate.js
> +    const [bearer, token] = req.headers.authorization.split(' ')
Добавила проверку

2021-11-22 12:48 UTC, yaroslava-yemets commented on routes/api/auth.js
> +router.get('/logout', authenticate, controllerWrapper(ctrl.logout))
Добавила

2021-11-22 20:30 UTC, KirillKulakow commented on controllers/auth/current.js
> +  console.log(_id)
лишние консоли

2021-11-22 20:32 UTC, KirillKulakow commented on controllers/auth/current.js
> +  if (!token) {
лишняя проверка - эта проверка выполняется в миддлваре

2021-11-22 20:34 UTC, KirillKulakow commented on controllers/contacts/listContacts.js
> +  if (isNaN(page) || isNaN(limit)) {
какое бы число ты не поставила бы в page или лимит - у тебя теперь будет ошибка
если не поймешь в чем промах - я в слаке)

2021-11-22 20:35 UTC, KirillKulakow requested changes
Need fix

2021-11-22 22:17 UTC, yaroslava-yemets commented on controllers/auth/current.js
> +  console.log(_id)
Удалила

2021-11-22 22:17 UTC, yaroslava-yemets commented on controllers/auth/current.js
> +  if (!token) {
Удалила

2021-11-22 22:25 UTC, yaroslava-yemets commented on controllers/contacts/listContacts.js
> +  if (isNaN(page) || isNaN(limit)) {
Проверила возможные варианты, но когда число срабатывает, а когда не число то не работает

2021-11-23 19:01 UTC, KirillKulakow approved these changes

2021-11-23 21:15 UTC, merged